# Generated by Django 2.1.5 on 2019-03-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('notice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_Name', models.CharField(max_length=255)),
                ('Room_Number', models.IntegerField()),
                ('Bed_Availabel', models.IntegerField()),
                ('Student_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
                ('Registration_Number', models.IntegerField()),
                ('Student_Name', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=10)),
                ('Course', models.CharField(max_length=100)),
                ('Blood_Group', models.CharField(max_length=4)),
                ('Date_of_birth', models.DateField()),
                ('Mobile_Number', models.IntegerField()),
                ('Mobile_Number2', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254)),
                ('Father_Name', models.CharField(max_length=255)),
                ('Father_Mobile_Number', models.IntegerField()),
                ('Father_Mobile_Number2', models.IntegerField()),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Hostel_Fees', models.CharField(max_length=255)),
                ('Mess_Fees', models.CharField(max_length=255)),
                ('Room_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Room')),
            ],
        ),
    ]
