# Generated by Django 2.1.5 on 2019-05-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='Mobile_No',
        ),
        migrations.RemoveField(
            model_name='complain',
            name='Student_Name',
        ),
    ]
