# Generated by Django 2.1.5 on 2019-05-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190510_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='Subject',
            new_name='subject',
        ),
    ]
