# Generated by Django 2.1.5 on 2019-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190510_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='email',
            field=models.CharField(default='xyz', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='mobile_no',
            field=models.IntegerField(default=8494959303),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complain',
            name='student_name',
            field=models.CharField(default='xyz', max_length=255),
            preserve_default=False,
        ),
    ]
