# Generated by Django 2.1.5 on 2019-05-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190510_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='mobile_no',
            new_name='roll_no',
        ),
    ]
