# Generated by Django 2.1.5 on 2019-05-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190510_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='Date',
        ),
    ]
