# Generated by Django 2.1.5 on 2019-05-13 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
